### ISSUE TITLE
lua error '__mul' (number expected, got nil) when spawning player

### ISSUE THREAD

**Issue by X-Coder** [ZionDevelopers/playx#100]
Hi, recently this error shows up when I spawn the main player. Maybe caused by the latest October gmod update?

> 
> [PlayX] lua/entities/gmod_playx/cl_init.lua:258: bad argument #2 to '__mul' (number expected, got nil)
> 1. __mul - [C]:-1
> 2. GetProjectorTrace - lua/entities/gmod_playx/cl_init.lua:258
> 3. ResetRenderBounds - lua/entities/gmod_playx/cl_init.lua:268
> 4. UpdateScreenBounds - lua/entities/gmod_playx/cl_init.lua:118
> 5. unknown - lua/entities/gmod_playx_repeater/cl_init.lua:33

**Comment by juliocoliveira** [comment]
Indeed is caused by the last GMOD update as always Garry keeps breaking our addons.
Well the problem is only to screens / monitors, You still can use the projectors. I'll take a look to the issue.
Thanks for reporting.

**Comment by X-Coder** [comment]
Thank you for fixing this so fast. This fixed the error on the screens, but now the projectors are spawning the projection on wrong angle.

I think I have a solution, I will create a patch in a few minutes when I'm finished testing.
