### ISSUE TITLE
Unsafe JavaScript attempt to access frame with URL : ... Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by iAmSneaky** [ZionDevelopers/playx#102]
Hello i have an issue when i load a video the frame is flashing white and i have 2 types errors on the dev console.

[a part of the dev console log.txt](https://github.com/ZionDevelopers/playx/files/693764/a.part.of.the.dev.console.log.txt)

I did a little video to show you but it's too large for GitHub if you want to see it just ask 😄 

I hope this "bug" will be fixed soon bye 👍

**Comment by juliocoliveira** [comment]
That is not a bug, That is a warning of Google Chrome Embedded of Awesomium API.
And there is nothing i can do to hide it, And there is nothing wrong with that, Just ignore it

**Comment by juliocoliveira** [comment]
And [ERROR] addons/playx/lua/entities/gmod_playx/cl_init.lua:258: bad argument #2 to '__mul' (number expected, got nil) is already fixed, Just update it.
