### ISSUE TITLE
Opening certain URLs in non-browsable provider and then closing causes a hard CTD for all clients

### ISSUE THREAD

**Issue by Krylia** [ZionDevelopers/playx#105]
I'm not gonna give any example URL's here. Go experiment. Plenty of URL's do this shit.

**Comment by Adam759** [comment]
I will definitely look into this. A lot of stuff is changing right now so things may become slightly unstable. Thank you for reporting

**Comment by Adam759** [comment]
You are going to have to give me at least one example URL here because I just tested over 20 URL's by opening them with non-browsable webpage and then closing them with the close media button and none of them crashed my client or any other clients on the server. I will continue to test but more information would be beneficial.

**Comment by Adam759** [comment]
Upon further testing, I could get it to happen if a file were to be opened with the non-browsable webpage provider, such as https://drive.google.com/uc?export=download&id=0B0JMGMGgxp9WMEdWb1hyQUhlOWs . (This link points to a google drive video download source). I will look into why that is happening. I am aware that there are some issues surrounding google drive right now as well and I am looking into that as well.

**Comment by Krylia** [comment]
It also occurs with some file links that are non-google drive related. Despite the following link being rather... unsavory... it does reproduce the issue: [](http://2girls1cup.ca/wp-content/uploads/2015/03/2girls1cupvideo.mp4?_=1)

**Comment by Adam759** [comment]
This issue has resurfaced again and will need more investigation. Seems to happen with raw file input or with attempted playback with JWPlayer of .mp4 content, even in Awesomium. The browser seems to hang up, may be an internal issue that is not directly related to our player.
