### ISSUE TITLE
Add Workaround Fix for YouTube Pausing

### ISSUE THREAD

**Issue by Adam759** [ZionDevelopers/playx#106]
Add a button to reinit the player at the current time and keep start at progression and all else preserve by adding it in as a soft reinit and seek to current start at progression

**Comment by juliocoliveira** [comment]
There is a bug, Something to do with click on screen, That Garry's mod Interface.
I guess it is on \lua\entities\gmod_playx, When you are on Q Menu, or Tab, If you click on the view / screen the video pause.

I think i made a fix for that on the old-dev branch, But i don't remember.
I'll see if go back on developing PlayX some more, because I'm unemployed now for some time, And I'll working freelances at home.

Some anything, Talk to me, I'll be glad to help! 👍

**Comment by Adam759** [comment]
The bug that this was targeting was the random freezing in videos. From my investigation this seems to be related to buffering. Youtube will just stop buffering the video, probably related to Awesomium being so old. 

I am working on another fix: just make flash the primary player. Swamp Cinema has done this and there are no issues. It is unfortunate being Awesomium supports WebM, but it is quite buggy in regards to the random pausing.

The fix that is explained above was a temporary fix to just reinitialize the player at the current spot to jump start buffering again. 

Let me know if you find anything else into this issue as well

**Comment by Adam759** [comment]
I am going to be uploading the fix in the next couple of days. I am essentially going to be forcing YouTube to use Flash if the client has it. If they client doesn't have flash it will fall back to HTML5. If people want to fix the pausing issue, they will have to install NPAPPI Flash, for now at least, until CEF is integrated.

**Comment by X-Coder** [comment]
Commit https://github.com/ZionDevelopers/playx/commit/7e7d48b3814e06c7a8a27206b28d74964ecbeb51#diff-936f61e794cfc90feb936f5d93b04c15R170 which fixed youtube volume introduced the click-on-screen bug @juliocoliveira mentioned. I will commit a patch for it.

**Comment by X-Coder** [comment]
The only issue with this is, it disables mouse input on the playx screen completely. Don't know if this was used by anyone. It allowed to control the webpage on the client-side screen while holding C-key.

**Comment by X-Coder** [comment]
The only issue with this is, it disables mouse input on the playx screen completely. Don't know if this was used by anyone. It allowed to control the webpage on the client-side screen while holding C-key.
