### ISSUE TITLE
Youtube LiveStream Error

### ISSUE THREAD

**Issue by ZyaTheInfestor** [ZionDevelopers/playx#112]
[ERROR] lua/playx/providers/livestream.lua:59: attempt to concatenate local 'clipID' (a nil value)
  1. GetPlayer - lua/playx/providers/livestream.lua:59
   2. ResolveProvider - lua/playx/playx.lua:243
    3. OpenMedia - lua/playx/playx.lua:295
     4. unknown - lua/playx/playx.lua:585
      5. unknown - lua/includes/modules/concommand.lua:54

**Comment by juliocoliveira** [comment]
That is not Youtube, that's https://livestream.com/
