### ISSUE TITLE
PlayX sometimes works and sometimes does not

### ISSUE THREAD

**Issue by nuclearSpectre** [ZionDevelopers/playx#116]
I don't know if anybody else has this problem:

"PlayX: Playing http://ziondevelopers.github.io/playx/youtubehost.html?url=https://youtube.com/watch?v=yeApSJBf318 using handler YoutubeNative
PlayX: Received metadata via provider YouTube
[HTML] Unable to post message to https://www.youtube.com. Recipient has origin http://ziondevelopers.github.io.

PlayX: Metadata received
[HTML] Unsafe JavaScript attempt to access frame with URL http://ziondevelopers.github.io/playx/youtubehost.html?url=https://youtube.com/watch?v=yeApSJBf318&start=0 from frame with URL https://www.youtube.com/embed/yeApSJBf318?autoplay=1&showinfo=0&cc_load_policy=0&iv_load_policy=3&disablekb=1&modestbranding=1&rel=0&controls=0&start=0&enablejsapi=1&origin=http%3A%2F%2Fziondevelopers.github.io&widgetid=1. Domains, protocols and ports must match.

PlayX: Page loaded, preparing to inject
[HTML] Unsafe JavaScript attempt to access frame with URL http://ziondevelopers.github.io/playx/youtubehost.html?url=https://youtube.com/watch?v=yeApSJBf318&start=0 from frame with URL https://www.youtube.com/embed/yeApSJBf318?autoplay=1&showinfo=0&cc_load_policy=0&iv_load_policy=3&disablekb=1&modestbranding=1&rel=0&controls=0&start=0&enablejsapi=1&origin=http%3A%2F%2Fziondevelopers.github.io&widgetid=1. Domains, protocols and ports must match. "

Sometimes, this addon will work and load any youtube link and other times, it will be stuck on a never ending buffer and just not play anything then spam the developer console with this. I've looked through the PlayX console command and try enabling and disabling it, like a refresh but nothing doing.

**Comment by juliocoliveira** [comment]
The message "[HTML] Unsafe JavaScript attempt to access frame with URL" its not a bug or error, Its just info.

And if you use the chromium branch of garrys mod it should work.
