### ISSUE TITLE
Licence Mismatch

### ISSUE THREAD

**Issue by Thepenguin9** [ZionDevelopers/playx#119]
Hey I noticed an incorrect licence is being used for the code, it's meant to be the GNU v3 licence

**Comment by juliocoliveira** [comment]
It's right. I changed.

**Comment by Thepenguin9** [comment]
Dude you can't just change the licence like that

**Comment by juliocoliveira** [comment]
Yes I can. The owner don't see an Issue, I don't see why you are wasting our time.

**Comment by Thepenguin9** [comment]
There are still files with code which are exclusively covered by the GPL licence. Please just change the licence back
