### ISSUE TITLE
YouTube query: No video found for query 'nil' when trying to use !ytplay

### ISSUE THREAD

**Issue by Titanic4** [ZionDevelopers/playx#122]
Any time I try to use !ytplay I get the message "YouTube query: No video found for query 'nil'" when PlayX is attempting to query YouTube for the video with the search query. After modifying the addon in such a way that the detailed error info is displayed in such case, I've got the response from Youtube telling me that the API quota was exceeded, along with HTTP 403 error, which is most likely the reason why the command doesn't work in the first place.

**Comment by Bryantdl7** [comment]
Most likely the developer's API key is overloaded. Media player suffers from a similar problem. If you want this to be fixed you could code in your own API key for your server.

**Comment by juliocoliveira** [comment]
Fixed
