### ISSUE TITLE
Navigator stopped working

### ISSUE THREAD

**Issue by juliocoliveira** [ZionDevelopers/playx#124]
For some reason the navigator are not working anymore, its not showing the changed url on the textbox and the video detection, closing, and playing on PlayX are not working either.
There is no errors to try to find what is the issue.

Need to do some testing and investigation, probably garry did some breakage there.

**Comment by TR094** [comment]
it seems like when you frist spawn a media player it doesnt work.
 tho if u remove it and spawn it again it seems that it does work.

**Comment by TR094** [comment]
update: ok now this is strange... on sam's media player it seemed that the navigator worked normall on without the cefcodecfix. but after i got it installed again not it doesnt seem to work at all? like i can launch the navigator yes, but it doesnt change the url's on the top.

**Comment by juliocoliveira** [comment]
Yeah, probably is a CEF Codec Fix bug, try to remove the code fix, very integrity of gmod and see if PlayX's navigator works, if does not, then garry broke it, If it does, so is a CEF Codec Fix bug and you cloud send a issue on their page, so it gets fixed, I'll keep the fix because of Twitch, so we have to wait to see.

**Comment by TR094** [comment]
ok ive gotten the hang of it, its not cefcodecfix its the actual media player that has the problem. it still doesnt show anything even without the cefcodecfix. it seems that the navigator only works like 10% of the time. (oh yeah playx navigator still doesnt work)

**Comment by TR094** [comment]
oh yeah how did the navigator even work back then? is it like media player where u click on a youtube video and then click ''request url''?

**Comment by TR094** [comment]
i found someone else made a navigator that works flawlessly, now i just need to make it work with playx

**Comment by TR094** [comment]
i could provide you the code and you could try to integrate it yourself
