### ISSUE TITLE
Youtube Live streams not working

### ISSUE THREAD

**Issue by TR094** [ZionDevelopers/playx#126]
just spits an error and nothing else

![youtuberror](https://github.com/ZionDevelopers/playx/assets/109485492/c85efa2c-71b5-452a-b3cf-6ebdb9480ad1)

**Comment by juliocoliveira** [comment]
I need that error. can you post it?

**Comment by TR094** [comment]
it doesnt make an lua error for some reason, just a youtube one, ill look at the code if theres something that could
be improved

**Comment by juliocoliveira** [comment]
![logo](https://steamuserimages-a.akamaihd.net/ugc/2046369901410372993/1562BF6FD72FFE932978DD3E393AE09B269DE052/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

https://steamcommunity.com/sharedfiles/filedetails/?id=2986445406 

I just tested it, it is working just fine with lives. Maybe your URL is wrong.

**Comment by juliocoliveira** [comment]
You can test here: http://ziondevelopers.github.io/playx/youtubehost.html?v=jfKfPfyJRdk

**Comment by TR094** [comment]
oh i know what the porlbem was, ive recently factory resetted gmod so it got rid of the cefcodecfix files and fixes, my bad ._.
