### ISSUE TITLE
PlayX will sometimes take up whole screen instead of media screen

### ISSUE THREAD

**Issue by thapatman54** [ZionDevelopers/playx#138]
Whenever I am attempting to play media, instead of playing on the screen of the object in question, it will play full screen on my monitor. It also does this as well with the music player.

Here is a screenshot
![image](https://github.com/ZionDevelopers/playx/assets/47374428/3ea8ab62-3bae-402c-a50e-e505cc1d8090)

**Comment by juliocoliveira** [comment]
Yes, that is by design, there is a new feature called full-screen, That is activated by pressing Shift+Enter or using the context-menu -> PlayX -> Fullscreen
