### ISSUE TITLE
Twitch.Tv cannot play

### ISSUE THREAD

**Issue by XxLegoTadhgxX** [ZionDevelopers/playx#79]
![gmt_lobby2_r30006](https://cloud.githubusercontent.com/assets/10999535/6982019/44b2d5d6-d9fb-11e4-835b-8e05ea2fb81c.jpg)
When I try watch a cast I cannot play it. It gets stuck on a pause. Any help?

**Comment by juliocoliveira** [comment]
I just tested, and is working fine: http://youtu.be/NKSIADhoS4U 

Try uncheck the Only play videos near me, or try other live channel or try open it again.
