### ISSUE TITLE
Youtube API upgrade required

### ISSUE THREAD

**Issue by titanic4** [ZionDevelopers/playx#80]
Trying to watch ANY video via playx ends with the video set by Youtube telling the user that device or app is using unsupported version of API. Can you look into it?

**Comment by juliocoliveira** [comment]
No, It is working fine, No Warnings or messages.
Make sure that the server that you are playing on is using an updated version of PlayX, Or if you are playing local make sure that your PlayX is from workshop and it is updated as well.

Make sure to leave maked JW Player on Administrative.

**Comment by titanic4** [comment]
Technically search query via !ytplay is a problem since it’s using API. By using Navigator or by pasting URL after !ytplay the addon can still play videos.  



Od: Júlio C. Oliveira
Wysłano: ‎wtorek‎, ‎28‎ ‎kwietnia‎ ‎2015 ‎00‎:‎10
Do: ZionDevelopers/playx
DW: titanic4

**Comment by juliocoliveira** [comment]
OK, tonight i'll look into it (UTC -03:00)

**Comment by juliocoliveira** [comment]
Indeed, i just tested it, But it need a complete rewrite on the PlayX query.
I don't know when i'll have time to do it.

**Comment by juliocoliveira** [comment]
Seams that SwadicalRag fixed that problem, On #81 but i did not tested yet.
I'll test tonight and then publish to Workshop.
