### ISSUE TITLE
Youtube Metadata(not the search) still uses old youtube API

### ISSUE THREAD

**Issue by adosikas** [ZionDevelopers/playx#82]
The queryed metadata via http://gdata.youtube.com/feeds/api/videos/ is displaying the deprecation video, this does affects the wire outputs.

The new API seems to have a equivalent here: https://developers.google.com/youtube/v3/docs/videos/list

**Comment by juliocoliveira** [comment]
No is not, As you can see on https://github.com/ZionDevelopers/playx/blob/master/lua/autorun/server/playx_media_query.lua#L92 Make sure you are using an Updated version.

**Comment by adosikas** [comment]
Not the search, i refer to the Metadata used to populate the wire outputs.

https://github.com/ZionDevelopers/playx/blob/master/lua/playx/providers/youtube.lua#L91

**Comment by juliocoliveira** [comment]
Well i don't have time to research on youtube api to re-implement this again, since i did not made this implementation.

But @SwadicalRag did the last youtube api upgrade just a few days ago, you would ask to he fix it.

**Comment by SwadicalRag** [comment]
I totally forgot about fixing metadata on my initial commit. Sorry!

It should be fixed in the PR I sent.

**Comment by juliocoliveira** [comment]
I tested, and worked fine but it gives the error:

[ERROR] addons/playx/lua/playx/providers/youtube.lua:128: attempt to index field
 'standard' (a nil value)
  1. onsuccess - addons/playx/lua/playx/providers/youtube.lua:128
   2. unknown - lua/includes/modules/http.lua:34

@SwadicalRag can you fix it?

**Comment by SwadicalRag** [comment]
What video was playing when that error occured?

I quickly skimmed the code, and there is no tabe called "standard", nor is anything called "standard" being indexed.

**Comment by juliocoliveira** [comment]
I don't know, i played a lot of videos.
https://github.com/ZionDevelopers/playx/blob/master/lua/playx/providers/youtube.lua#L128

**Comment by adosikas** [comment]
Should probably be "default" in that line, not "standard"
Excerpt of a API result for example

    "snippet": {
      [...]
      "thumbnails": {
       "default": {
        "url": "https://i.ytimg.com/vi/JVSZwOpKVCY/default.jpg"
       },
       "medium": {
        "url": "https://i.ytimg.com/vi/JVSZwOpKVCY/mqdefault.jpg"
       },
        "high": {
        "url": "https://i.ytimg.com/vi/JVSZwOpKVCY/hqdefault.jpg"
       }
      },
      [...]
     }

**Comment by SwadicalRag** [comment]
Ah, a simple control+F didn't work when i tried it.

@adosikas is correct, 'standard' was apparently undefined in that api call, whilst 'default' will always be defined.

I'm not near my computer at the moment, so I can't make any changes myself.
