### ISSUE TITLE
No video or sound, just the title.

### ISSUE THREAD

**Issue by Drexan** [ZionDevelopers/playx#85]
When I open a video URI/URL it just displays the title of the youtube video and no sound is made.

**Comment by juliocoliveira** [comment]
Make sure you used a Projector Entity not a Radio, Check if "Use an improved player when applicable" is checked, Check if "Use low frame rate" is unchecked, And check if you have the right Adobe Flash Player installed, If you not sure close your garry's mod and run the uninstaller then installer from the zip located on the description (If you are a Windows user).

If you are a linux user you need do the tutorial on the workshop description.
If you are a Mac OS X user, as you can see on the description, It is not supported.
