### ISSUE TITLE
Can't play Hulu?

### ISSUE THREAD

**Issue by DubyaDude** [ZionDevelopers/playx#86]
Ok, so I am currently using the latest version of PlayX and I can't seem to play any hulu videos.
It keeps saying "This video is not currently available at this site, but you can view this and other Hulu videos at Hulu.com"
Screenshot: http://steamcommunity.com/sharedfiles/filedetails/?id=495084164

For Example I attempt to play "http://www.hulu.com/watch/332029" and I get that error

EDIT------

Also I tried doing the original link "http://www.hulu.com/watch/332029#i1,p0,d0" it says "No Provider was auto-detected"

**Comment by juliocoliveira** [comment]
That is not a issue we can solve.
That video is locked to be available only on hulu.
Try other videos, the #i1,p0,d0 means nothing.

**Comment by DubyaDude** [comment]
Understood, can I get examples of what would work for Hulu?

**Comment by juliocoliveira** [comment]
Hulu is only available on some countries, Mine is not included, So i cannot help you.
