### ISSUE TITLE
Lua Error when adding bookmark from Administrate

### ISSUE THREAD

**Issue by Qwerty-Space** [ZionDevelopers/playx#87]
[ERROR] lua/playx/client/bookmarks.lua:306: attempt to call method 'AddLine' (a nil value)
1. AddBookmark - lua/playx/client/bookmarks.lua:306
   1. fnEnter - lua/playx/client/playx.lua:789
   2. DoClick - lua/derma/derma_utils.lua:231
      1. unknown - lua/vgui/dlabel.lua:218

**Comment by juliocoliveira** [comment]
I'll see that

**Comment by juliocoliveira** [comment]
I don't got any errors on the bookmarks, Make sure to have the PlayX updated from this repository or from the workshop.
