### ISSUE TITLE
PlayX error, not able to play videos.

### ISSUE THREAD

**Issue by MrCoderwhite** [ZionDevelopers/playx#89]
[PlayX] lua/playxlib.lua:147: attempt to index local 'str' (a nil value)
  1. FindMatch - lua/playxlib.lua:147
   2. Detect - lua/playx/providers/youtube.lua:25
    3. ResolveProvider - lua/playx/playx.lua:241
     4. OpenMedia - lua/playx/playx.lua:294
      5. Play - lua/autorun/server/playx_media_query.lua:120
       6. successF - lua/autorun/server/playx_media_query.lua:149
        7. onsuccess - lua/autorun/server/playx_media_query.lua:101
         8. unknown - lua/includes/modules/http.lua:34

this error also follows up sometimes, same "symptoms"

Undefined state DS_BEGIN_NO_PLAYER; please report error

**Comment by juliocoliveira** [comment]
Is a temporary bug, The normal plays like !playx ytvideo and navigator works fine.
.ytplay works sometimes and it will be fixed
