### ISSUE TITLE
Kissanime Support

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [ZionDevelopers/playx#91]
Mind adding kissanime support? Aka support for google video links like `https://r1---sn-n0gxfxnu-hjpe.googlevideo.com/videoplayback?requiressl=yes&id=bc581959d9234fbf&itag=22&source=webdrive&ttl=transient&app=texmex&ip=68.70.87.64&ipbits=32&expire=1467448803&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,pl,requiressl,source,ttl&signature=7B36D6CA53F2E7F2DF514479E639CB9D9219379A.67769678CE91718C7FD4A93B893F8DAB7DAB0EE7&key=cms1&pl=19&cms_redirect=yes&mm=31&mn=sn-n0gxfxnu-hjpe&ms=au&mt=1467436969&mv=m&ir=1&rr=12`

**Comment by juliocoliveira** [comment]
No.
But you can do it yourself, Like: http://steamcommunity.com/sharedfiles/filedetails/?id=344710649
