### ISSUE TITLE
idfk what the title should be called 

### ISSUE THREAD

**Issue by bjoern90** [ZionDevelopers/playx#94]
but when i play videos i see those
![20160713040152_1](https://cloud.githubusercontent.com/assets/12915146/16789599/605d8a3c-48af-11e6-97f9-d387e184dd0a.jpg)

i hope you fix those..

**Comment by juliocoliveira** [comment]
IT IS FIXED! Update it!

**Comment by xenon149** [comment]
This is not fixed @juliocoliveira

**Comment by juliocoliveira** [comment]
Try update it, It its.
