### ISSUE TITLE
Feature Request - Youtube Source (Google Video) Support

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [ZionDevelopers/playx#95]
The google drive addon works well, however it'd save the large amount of time to simply have a native support for Google Video, instead of downloading videos from Kissanime and uploading them to google drive. 
Google Video URL Example -
 https://r3---sn-n0gxfxnu-hjpe.googlevideo.com/videoplayback?requiressl=yes&id=e09e737f1df61c70&itag=22&source=webdrive&ttl=transient&app=texmex&ip=68.70.87.64&ipbits=32&expire=1468915358&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,pcm2cms,pl,requiressl,source,ttl&signature=5363D57186459D7B1438AD7FAB5CDF506B463E75.79C0897C6B8068206B8E98EACA474489DCB386B9&key=cms1&pl=19&cms_redirect=yes&mm=31&mn=sn-n0gxfxnu-hjpe&ms=au&mt=1468904329&mv=m&pcm2cms=yes

And yeah, I've tried using Non Browsable Webpage.
It only plays sound sadly...

**Comment by UnstableCodeScarlet** [comment]
Nevermind (Maybe), I found a pretty good workaround by using Frostanime.Tv, Simply click popout and it'll redirect you to a google drive url, which you can use with the Google Drive Addon.
So yeah, Kissanime won't work.
\sigh\ I hope this info gets posted on Playx somewhere, This caused me a ton of frustration.

**Comment by juliocoliveira** [comment]
Google Drive Addon is not mine, So i cannot updated it, Talk to the developer.
