### ISSUE TITLE
Error - PlayX Keeps Refreshing

### ISSUE THREAD

**Issue by Pilot1000** [ZionDevelopers/playx#96]
When using PlayX everything seems to go fine but when the video starts it just refreshes every second with this in console over and over again:

```
[HTML] Unable to post message to http://www.youtube.com. Recipient has origin http://ziondevelopers.github.io.

[HTML] Unable to post message to http://www.youtube.com. Recipient has origin https://www.youtube.com.

PlayX: Page loaded, preparing to inject
```

Until PlayX is shut off. Any fix?

**Comment by juliocoliveira** [comment]
It does not refresh, It loops, That is an issue with JWPlayer, use non JWPlayer instead if you want.
I cannot fix it, And i need wait for a fix from JWPlayer team, The "errors" are not errors just notice and have nothing to do with it.
