### ISSUE TITLE
Black Screen Unless Webpage

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [ZionDevelopers/playx#97]
Basically nothing but Non Browsable webpage is working.
EX:Youtube mode- http://puu.sh/qo0j3/a6cc91c1ea.jpg
EX:Non-Browsable Page Mode- http://puu.sh/qo0mK/93627749a1.jpg
Also tried with MP4 and FLV, as well as Google drive, Of course with different links.
Each only showed in Non browsable webpage mode.

**Comment by juliocoliveira** [comment]
Make sure that you have PlayX updated. Youtube is working just fine since was updated. And make sure that the server that you are playing is using an updated PlayX as well.

**Comment by UnstableCodeScarlet** [comment]
I'm pretty sure we are completely up to date.
Apparently some players can see it just fine occasionally, other times the same player cannot see it.
Strange bug is strange.
