### ISSUE TITLE
twitch 

### ISSUE THREAD

**Issue by std92050** [ZionDevelopers/playx#98]
i use playx to play twitch stream in sandbox mod , but it is always black screen. i try updating playx but

it still doesn't work. (it performan normally in cinema mod)

**Comment by TenLetterz** [comment]
I have the same problem
Here's what the console says when I'm using a twitch link

PlayX: Beginning media http://www.twitch.tv/gamesdonequick/embed with handler IFrame, start at 0s
PlayX: Metadata function available via provider twitch.tv
PlayX: Received metadata via provider twitch.tv
TenLetters started a video!
PlayX: Playing http://www.twitch.tv/gamesdonequick/embed using handler IFrame
[HTML] Uncaught TypeError: Cannot assign to read only property '__esModule' of #<Object>
[HTML] Uncaught TypeError: undefined is not a function
PlayX: Page loaded, preparing to inject

**Comment by TenLetterz** [comment]
Is this github even active anymore? The profiles of the addon's creators are all privated so we can't directly message them about this.

**Comment by juliocoliveira** [comment]
This project is active, But i was working a lot and, Garry updated garrysmod and fucked somethings, And Twitch was brought by amazon, so lots of things stopped working.

You need flash for other browsers on windows http://ziondevelopers.github.io/playx/flash_win.zip and Mac is not supported, And linux there is a tutorial on http://steamcommunity.com/groups/playx/discussions/0/630802344298583475/

Any message that starts with [HTML] you can ignore it, Is not from the PlayX.  Is just notices from javascript inside the browser.

Any Lua ERRORS you should submit.

**Comment by juliocoliveira** [comment]
Make sure that the server you are playing on have PlayX updated. And if singleplayer just use from the workshop. This repository is the official one, the original is outdated.

I'll check that is wrong and fix twich soon. i'll test and fix watch is wrong with twitch

**Comment by juliocoliveira** [comment]
Just use the projector, It works fine. The video screens is complicated, because most are just a block 4:3, and all the new videos is 16:9 there is nothing i'll do about that.

If you want the original, Use the Projector, the video will match just fine.

**Comment by juliocoliveira** [comment]
I temporary removed twitch.tv.

If any of the former(s) (or new) contributor(s) want they can submit a pull request to the new twitch.tv api, since it is still a mess, And Gmod's Awesomium is still outdated as hell, So i guess don't support HTML5 yet.

**Comment by Adam759** [comment]
I have been looking to Twitch again since it is such a big provider. (I know this is an old issue, but just trying to see if I can do anything about it). I have been attempting to get the old twitch swf player to work, if anyone has any input or suggestions on it let me know. The API is easy to change over since it is just metadata and player control stuff, but the swf player needs to have the client_id in its own API calls, which might be impossible to do. Any ideas here would be very helpful.

**Comment by Adam759** [comment]
With Chromium, Twitch can now use PPAPI Flash as a h.264 backend to play the content, so Twitch will work if you switch to the chromium branch and install PPAPI flash. Once Chromium is pushed to the main branch, Twitch should work seamlessly once I get the default player switched over from the SWF player.

**Comment by juliocoliveira** [comment]
Added Twitch channel and vod support back again, but does not work with current garry's mod or branch x86-64 (chromium)
